Update MixedBeerBlockItem.java
Method required server side for slotlink mod:

java.lang.NoSuchMethodError: 'net.minecraft.class_2561 lekavar.lma.drinkbeer.item.MixedBeerBlockItem.getMixedBeerName(net.minecraft.class_1799)'